### ISSUE TITLE
how to decide which data to filter

### ISSUE THREAD

**Issue by djouallah** [liam-crow/qld_car_crash_data#1]
your presentation yesterday was fantastic, this is the first I think I understood what's stats is all about.
but I was a bit nervous about something you said, you basically removed some rows because if i remember thinks are an outlier, how do you decide what to remove ?

**Comment by liam-crow** [comment]
This mainly came to two points:

- The a situation only occurred once or twice in the whole dataset, so estimating it's effect can be tricky
- There were incomplete records, like no speed limit was recorded

Removal of these rows basically removed 50 entries from 12000 total entries

**Comment by djouallah** [comment]
thanks
